apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  image: 112989970690.dkr.ecr.us-east-1.amazonaws.com/legacy-ecommerce-app
  interval: 1m0s
