apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: flask-demo
data:
  ENABLE_CART: "true"
  ENABLE_RECOMMENDATIONS: "false"
  MAX_ITEMS_PER_PAGE: "20"
  CACHE_TIMEOUT: "300"
  DEBUG_MODE: "false"
