apiVersion: v1
kind: Service
metadata:
  name: flask-gitops-service
  namespace: flask-demo
spec:
  selector:
    app: flask-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
